# Container base
FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04

# Update package repositories
RUN apt-get update

# Install package dependencies
RUN apt-get install build-essential gdb git cmake cppcheck -y

